# Generated by Django 4.2.28 on 2026-02-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_verified_useractioncode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('professional', 'Professional')], default='free', max_length=20),
        ),
    ]
