# Generated by Django 4.2.28 on 2026-02-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
