# Generated by Django 4.2.28 on 2026-02-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_phone_user_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ka', 'Georgian')], default='en', max_length=10),
        ),
    ]
