# Generated by Django 4.2.28 on 2026-02-27 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('gateway', models.CharField(choices=[('bog', 'Bank of Georgia'), ('fastoo', 'Fastoo')], max_length=20)),
                ('plan', models.CharField(max_length=50)),
                ('amount_gel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GEL', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('gateway_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('payment_url', models.URLField(blank=True, default='')),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('webhook_payload', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('trial_started', 'Trial Started'), ('trial_ended', 'Trial Ended'), ('upgraded', 'Upgraded'), ('renewed', 'Renewed'), ('downgraded', 'Downgraded'), ('canceled', 'Canceled'), ('payment_confirmed', 'Payment Confirmed'), ('payment_failed', 'Payment Failed')], max_length=50)),
                ('from_tier', models.CharField(blank=True, default='', max_length=20)),
                ('to_tier', models.CharField(blank=True, default='', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_events', to='subscriptions.paymentsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='subscriptio_user_id_354fdc_idx'), models.Index(fields=['event_type', '-created_at'], name='subscriptio_event_t_ac4a4c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentsession',
            index=models.Index(fields=['user', '-created_at'], name='subscriptio_user_id_36b1a7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsession',
            index=models.Index(fields=['order_id'], name='subscriptio_order_i_8301d6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsession',
            index=models.Index(fields=['status', '-created_at'], name='subscriptio_status_5150bb_idx'),
        ),
    ]
