# Generated by Django 4.2.28 on 2026-02-25 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(choices=[('analyze_cv', 'Analyze CV'), ('improve_section', 'Improve Section'), ('check_ats', 'Check ATS'), ('tailor_for_job', 'Tailor for Job'), ('translate_cv', 'Translate CV'), ('generate_cover_letter', 'Generate Cover Letter')], max_length=50)),
                ('success', models.BooleanField(default=False)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'feature', '-created_at'], name='ai_aiusage_user_id_633ad9_idx'), models.Index(fields=['user', '-created_at'], name='ai_aiusage_user_id_1cad65_idx')],
            },
        ),
    ]
