# Generated by Django 4.2.28 on 2026-02-24 17:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cvs', '0002_cv_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('cv_data', models.JSONField(blank=True, default=dict)),
                ('section_order', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(max_length=5)),
                ('template', models.CharField(max_length=32)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cvs.cv')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cv', '-created_at'], name='cv_versions_cv_id_62c282_idx')],
            },
        ),
    ]
