# Generated by Django 4.2.28 on 2026-02-23 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled CV', max_length=255)),
                ('cv_data', models.JSONField(blank=True, default=dict)),
                ('section_order', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(choices=[('en', 'English'), ('ka', 'Georgian')], default='en', max_length=5)),
                ('template', models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('minimal', 'Minimal')], default='modern', max_length=32)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_archived', '-updated_at'], name='cvs_cv_user_id_bf6419_idx')],
            },
        ),
    ]
