# Generated by Django 4.2.28 on 2026-02-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('cvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='cvs', to='labels.label'),
        ),
    ]
