import React, { createContext, useContext, useState, useEffect, useCallback } from "react";

const STORAGE_KEY = "nebula_lang";

const translations = {
  en: {
    // Nav / Header
    "nav.home": "Home",
    "nav.templates": "Templates",
    "nav.workspace": "Workspace",
    "nav.logout": "Logout",
    "nav.getStarted": "Get Started",
    "nav.pricing": "Pricing",
    "nav.contact": "Contact",
    "nav.langEnglish": "GB English",
    "nav.langGeorgian": "GE ქართული",
    // Resume section titles (for labels & PDF)
    "resume.experience": "Experience",
    "resume.education": "Education",
    "resume.skills": "Skills",
    "resume.summary": "Summary",
    "resume.downloadPdf": "Download PDF",
    "resume.save": "Save",
    "resume.personalInfo": "Personal Information",
    "resume.professionalSummary": "Professional Summary",
    "resume.workExperience": "Work Experience",
    "resume.projects": "Projects",
    "resume.languages": "Languages",
    "resume.certificates": "Certificates",
    "resume.present": "Present",
    // Dashboard
    "dashboard.hi": "Hi",
    "dashboard.logout": "Logout",
    "dashboard.myWorkspace": "My Workspace",
    "dashboard.my": "My",
    "dashboard.workspace": "Workspace",
    "dashboard.createNewResume": "Create New Resume",
    "dashboard.welcomeBack": "Welcome back",
    "dashboard.initializing": "Initializing Workspace...",
    "dashboard.freeTierActive": "Free Tier Active",
    "dashboard.resumes": "Resumes",
    "dashboard.pdfDownloads": "PDF Downloads",
    "dashboard.upgradeUnlimited": "UPGRADE FOR UNLIMITED",
    "dashboard.workspaceEmpty": "Your workspace is empty",
    "dashboard.workspaceEmptyDesc": "Ready to land your dream job? Pick a template and build your resume in minutes.",
    "dashboard.selectTemplate": "Select a Template",
    "dashboard.openEditor": "Open Editor",
    "dashboard.untitledResume": "Untitled Resume",
    "dashboard.freeLimitAlert": "Free tier is limited to 1 resume. Upgrade to Pro for unlimited!",
    "dashboard.deleteConfirm": "Are you sure? This cannot be undone.",
    "dashboard.duplicatePro": "Resume duplication is a Pro feature!",
    "dashboard.deleteFailed": "Delete failed. Please try again.",
    "dashboard.searchPlaceholder": "Search resumes...",
    // Editor
    "editor.resumeNamePlaceholder": "Resume Name...",
    "editor.saveChanges": "Save changes",
    "editor.export": "Export",
    "editor.generating": "Generating...",
    "editor.zoom": "Zoom",
    "editor.saved": "Saved",
    "editor.syncing": "Saving",
    "editor.unsavedChanges": "Unsaved Changes",
    "editor.connectionError": "Connection Error",
    "editor.addNewModule": "Add New Resume Module",
    "editor.reorder": "Reorder",
    "editor.addSection": "Add a Section",
    "editor.classic": "Classic",
    "editor.europass": "Europass",
    "editor.save": "Save",
    "editor.downloadPdf": "Download PDF",
    "editor.personalProfile": "Personal Profile",
    "editor.addContentSection": "Add Content Section",
    "editor.cloudSynced": "Cloud Synced",
    "editor.typing": "Typing...",
    "editor.syncError": "Sync Error",
    "editor.ats": "ATS",
    "editor.tailor": "Tailor",
    "editor.improve": "Improve",
    "editor.analyze": "Analyze",
    "editor.history": "History",
    // Form labels (UI only)
    "form.fullName": "Full Name *",
    "form.jobTitle": "Job Title",
    "form.email": "Email",
    "form.phone": "Phone",
    "form.location": "Location",
    "form.linkedin": "LinkedIn",
    "form.profilePicture": "Profile Picture",
    "form.profilePictureHint": "Professional photos increase visibility.",
    "form.square": "Square",
    "form.circle": "Circle",
    "form.company": "Company",
    "form.startDate": "Start Date",
    "form.endDate": "End Date",
    "form.currentlyWorking": "Currently working here",
    "form.description": "Description",
    "form.addEntry": "Add Entry",
    "form.deleteSection": "Delete Section",
    "form.aiImprove": "AI Improve",
    "form.addSkill": "Add Skill",
    "form.schoolUniversity": "School / University",
    "form.degreeMajor": "Degree / Major",
    "form.city": "City",
    "form.country": "Country",
    "form.addEducation": "Add Education",
    "form.addProject": "Add Project",
    "form.addLanguage": "Add Language",
    "form.addCertificate": "Add Certificate",
    "form.projectName": "Project Name",
    "form.projectLink": "Project Link (Optional)",
    "form.certificateName": "Certificate Name",
    "form.issuer": "Issuer (e.g. Google)",
    "form.date": "Date",
    "form.deleteSectionConfirm": "Delete this entire section?",
    "form.deleteExperienceConfirm": "Are you sure you want to delete the entire",
    "form.section": "section?",
    // ATS Panel
    "ats.whatIs": "What is ATS? Companies use Applicant Tracking Systems to automatically screen CVs before a human ever sees them. A higher score means your CV passes more automated filters and reaches a recruiter.",
    "ats.title": "ATS Checker",
    "ats.subtitle": "Applicant Tracking System",
    "ats.proFeature": "ATS Checker is a Pro Feature",
    "ats.upgradeToPro": "Upgrade to Pro to check your ATS compatibility score and get actionable fixes. 20 checks per month included.",
    "ats.upgradeToProButton": "Upgrade to Pro — 29.99 ₾/mo",
    "ats.maybeLater": "Maybe later",
    "ats.targetRole": "Target Role",
    "ats.targetRoleOptional": "optional — improves accuracy",
    "ats.industry": "Industry",
    "ats.industryOptional": "optional",
    "ats.placeholderTargetRole": "e.g. Frontend Developer",
    "ats.placeholderIndustry": "e.g. Technology",
    "ats.monthlyLimitReached": "Monthly limit reached",
    "ats.usedAllChecks": "You've used all {n} ATS checks this month. Upgrade to Professional for unlimited checks.",
    "ats.upgradeToProfessional": "Upgrade to Professional",
    "ats.runCheck": "Run ATS Check",
    "ats.rerunCheck": "Re-run Check",
    "ats.left": "left",
    "ats.checkFailed": "ATS check failed. Please try again.",
    "ats.checkProFeature": "ATS Check is a Pro feature. Upgrade to continue.",
    // Tailor Panel
    "tailor.title": "Tailor for Job",
    "tailor.intro": "Paste the job description and the AI rewrites relevant sections to match the role's keywords. Nothing changes until you click Apply.",
    "tailor.jobTitle": "Job Title",
    "tailor.placeholderJobTitle": "e.g. Senior Frontend Dev",
    "tailor.company": "Company",
    "tailor.placeholderCompany": "e.g. Google",
    "tailor.jobDescription": "Job Description",
    "tailor.placeholderJobDescription": "Paste the full job description here. More detail = better match.",
    "tailor.pasteJob": "Paste job description for targeted tailoring…",
    "tailor.tailoring": "Tailoring your CV…",
    "tailor.tailorMyCv": "Tailor My CV",
    "tailor.strongMatch": "Strong match",
    "tailor.decentMatch": "Decent match",
    "tailor.weakMatch": "Weak match",
    "tailor.failed": "Tailoring failed. Please try again.",
    // Improve Panel
    "improve.title": "AI Improve",
    "improve.pickSection": "Pick a section to improve",
    "improve.pickSectionDesc": "Pick a section. The AI rewrites it — you see the original and the suggestion side by side, and can edit it before applying.",
    "improve.generatingSuggestion": "Generating suggestion…",
    "improve.reviewBeforeApplying": "Review before applying",
    "improve.upgradeToContinue": "Upgrade to continue",
    "improve.clickToImprove": "Click to improve with AI",
    "improve.improving": "Improving your {section}…",
    "improve.gptRewriting": "GPT-4 is rewriting your content",
    "improve.usuallyTakes": "Usually takes 3–5 seconds",
    "improve.backToSections": "Back to sections",
    "improve.aiSuggestionsFor": "AI Suggestions for {section}",
    "improve.originalContent": "Original Content",
    "improve.aiImprovedVersion": "AI Improved Version",
    "improve.applySuggestions": "Apply Suggestions",
    "improve.editBeforeApplying": "Edit Before Applying",
    "improve.reject": "Reject",
    "improve.tryDifferent": "Try Different Version",
    // Analyze Panel
    "analyze.title": "CV Analysis",
    "analyze.subtitle": "Overall fit and recommendations",
    "analyze.whatDoes": "What does this do? Analyzes your CV against a job description and returns an overall score, strengths, areas to improve, and ATS notes. Optional: paste a job description for targeted feedback.",
    "analyze.jobDescription": "Job description",
    "analyze.jobDescriptionOptional": "optional",
    "analyze.placeholder": "Paste job description for targeted analysis…",
    "analyze.analyzeAgain": "Analyze again",
    "analyze.upgradeRequired": "CV Analysis is limited on Free plan. Upgrade to continue.",
    "analyze.failed": "CV analysis failed. Please try again.",
    // History Panel
    "history.title": "Version History",
    "history.notAvailable": "Version history is not available on Free plan.",
    "history.upgradeToSave": "Upgrade to Pro to save snapshots and restore previous versions.",
    "history.upgradeToPro": "Upgrade to Pro",
    "history.limitReached": "Version limit reached. Upgrade for more history.",
    "history.failedToLoad": "Failed to load versions.",
    "history.failedToSave": "Failed to save version.",
    "history.failedToRestore": "Failed to restore version.",
    // Landing Page
    "landing.badge": "AI-POWERED RESUME BUILDER",
    "landing.heroTitle": "Create a",
    "landing.heroTitleHighlight": "Stellar Resume",
    "landing.heroTitleEnd": "That Gets You Hired.",
    "landing.heroSubtitle": "Build a high-impact professional resume in minutes using advanced AI and designer-crafted templates.",
    "landing.getStartedFree": "Get Started Free",
    "landing.goToDashboard": "Go to Dashboard",
    "landing.browseTemplates": "Browse Templates",
    "landing.buildYourFuture": "Build your future",
    "landing.ctaTitle": "Ready to Build Your Dream Resume?",
    "landing.ctaSubtitle": "Join thousands of professionals who've landed their dream jobs with our AI-powered resume builder",
    "landing.ctaButton": "Start Building Now",
    "landing.footerTagline": "Create a stellar resume that shines across every job universe.",
    "landing.footerBrand": "Nebula AI CV Builder",
    "landing.footerCopyright": "© 2025 Nebula AI. All rights reserved.",
    "landing.footerPrivacy": "Privacy Policy",
    "landing.footerTerms": "Terms of Service",
    "landing.footerContact": "Contact",
    // Feature cards (landing)
    "landing.featuresTitle": "Everything You Need to Build a Perfect Resume",
    "landing.featuresSubtitle": "Powerful features designed to help you create professional resumes that get you hired",
    "landing.feature1Title": "Professional Template",
    "landing.feature1Desc": "Clean, ATS-friendly classic template designed for maximum impact.",
    "landing.feature2Title": "Full Customization",
    "landing.feature2Desc": "Customize colors, fonts, and layouts to match your personal brand perfectly.",
    "landing.feature3Title": "Export to PDF",
    "landing.feature3Desc": "Download your resume as a high-quality PDF ready to send to employers.",
    "landing.feature4Title": "AI-Powered",
    "landing.feature4Desc": "Get intelligent suggestions to enhance your resume content and stand out.",
    "landing.feature5Title": "Secure & Private",
    "landing.feature5Desc": "Your data is encrypted and stored securely. We never share your information.",
    "landing.feature6Title": "Quick Clone / Versioning",
    "landing.feature6Desc": "Create an exact copy of this CV to tailor it for a different job application or save a snapshot of your current progress.",
    "landing.learnMore": "Learn More",
    // Template Gallery
    "templates.chooseStyle": "Choose your style",
    "templates.chooseFoundation": "Choose a foundation",
    "templates.chooseFoundationSub": "for your next chapter.",
    "templates.subtitle": "Our templates aren't just designs—they are strategic tools built to get you through the door.",
    "templates.backToDashboard": "Back to Dashboard",
    "templates.backToHome": "Back to Home",
    "templates.professional": "Professional",
    "templates.creative": "Creative",
    "templates.academic": "Academic",
    "templates.aiOptimized": "AI Optimized",
    "templates.selectDesign": "Select Design",
    "templates.initializing": "Initializing...",
    "templates.interchangeable": "All templates are interchangeable. You can switch layouts at any time without losing your content.",
    "templates.proBadge": "Pro",
    "templates.upgradeToUnlock": "Upgrade to Unlock",
    "templates.europassName": "Europass Modern",
    "templates.europassRole": "International & Institutional",
    "templates.europassSummary": "The gold standard for EU public sectors, medicine, and academia.",
    "templates.europassIntro": "Engineered for complex credentials. This framework follows official European Commission standards, organizing multilingual skills and deep certifications into a perfectly structured, authoritative hierarchy.",
    "templates.europassF1": "EU Standards Compliant",
    "templates.europassF2": "Multi-page Optimization",
    "templates.europassF3": "Academic Structure",
    "templates.classicName": "Classic Professional",
    "templates.classicRole": "Corporate & Executive",
    "templates.classicSummary": "Optimized for high-growth tech, finance, and leadership roles.",
    "templates.classicIntro": "A precision-engineered layout that prioritizes 'skimmability'. Designed to beat ATS filters while presenting your career progression with an elegant, single-column focus that recruiters love.",
    "templates.classicF1": "99% ATS Pass Rate",
    "templates.classicF2": "Executive Readability",
    "templates.classicF3": "Impact-First Layout",
    // Pricing Page
    "pricing.heroTitle": "Simple, Transparent",
    "pricing.heroTitleHighlight": "Pricing",
    "pricing.heroSubtitle": "Prices in ₾ GEL · No hidden fees.",
    "pricing.heroSubtitleLine2": "Cancel anytime.",
    "pricing.trialBanner": "You have",
    "pricing.trialBannerDays": "day",
    "pricing.trialBannerDaysPlural": "days",
    "pricing.trialBannerEnd": "left on your free Pro trial. Upgrade now to keep all features.",
    "pricing.currentPlan": "Current Plan",
    "pricing.enterpriseTitle": "Need Enterprise?",
    "pricing.enterpriseDesc": "Team collaboration, white label, API access, custom storage,",
    "pricing.enterpriseDescLine2": "and phone support. Pricing on request.",
    "pricing.enterpriseCta": "Contact Sales",
    "pricing.trialBadge": "New accounts get a free 7-day Pro trial — no card required",
    "pricing.paymentError": "Payment initialization failed. Please try again.",
    // Common actions
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    // Plan: Free
    "pricing.free.name": "Free",
    "pricing.free.price": "0₾",
    "pricing.free.description": "Get started with the basics. No credit card needed.",
    "pricing.free.cta": "Get Started Free",
    "pricing.free.f1": "Up to 2 CVs",
    "pricing.free.f2": "PDF Downloads (with watermark)",
    "pricing.free.f3": "2 Templates (Classic & Europass)",
    "pricing.free.f4": "5 AI Improvements per section",
    "pricing.free.f5": "5 AI Full Analysis total",
    "pricing.free.f6": "ATS Score Checker",
    "pricing.free.f7": "Job Tailoring",
    "pricing.free.f8": "Cover Letter Generator",
    "pricing.free.f9": "CV Translation",
    "pricing.free.f10": "Version History",
    "pricing.free.f11": "10 MB Storage",
    // Plan: Pro Monthly
    "pricing.proMonthly.name": "Pro",
    "pricing.proMonthly.price": "29.99₾",
    "pricing.proMonthly.period": "/month",
    "pricing.proMonthly.description": "Everything you need to land your next job.",
    "pricing.proMonthly.cta": "Start Pro Monthly",
    "pricing.proMonthly.badge": "Most Popular",
    "pricing.proMonthly.f1": "Up to 20 CVs",
    "pricing.proMonthly.f2": "PDF Downloads (no watermark)",
    "pricing.proMonthly.f3": "2 Templates (Classic & Europass)",
    "pricing.proMonthly.f4": "Unlimited AI Improvements",
    "pricing.proMonthly.f5": "100 AI Full Analyses / month",
    "pricing.proMonthly.f6": "20 ATS Score Checks / month",
    "pricing.proMonthly.f7": "50 Job Tailorings / month",
    "pricing.proMonthly.f8": "Cover Letter Generator",
    "pricing.proMonthly.f9": "CV Translation",
    "pricing.proMonthly.f10": "Last 10 Version History",
    "pricing.proMonthly.f11": "500 MB Storage",
    // Plan: Pro Yearly
    "pricing.proYearly.name": "Pro Yearly",
    "pricing.proYearly.price": "239.99₾",
    "pricing.proYearly.period": "/year",
    "pricing.proYearly.description": "Same as Pro Monthly — save ~2 months free.",
    "pricing.proYearly.cta": "Start Pro Yearly",
    "pricing.proYearly.badge": "Save ~33%",
    "pricing.proYearly.f1": "Up to 20 CVs",
    "pricing.proYearly.f2": "PDF Downloads (no watermark)",
    "pricing.proYearly.f3": "2 Templates (Classic & Europass)",
    "pricing.proYearly.f4": "Unlimited AI Improvements",
    "pricing.proYearly.f5": "100 AI Full Analyses / month",
    "pricing.proYearly.f6": "20 ATS Score Checks / month",
    "pricing.proYearly.f7": "50 Job Tailorings / month",
    "pricing.proYearly.f8": "Cover Letter Generator",
    "pricing.proYearly.f9": "CV Translation",
    "pricing.proYearly.f10": "Last 10 Version History",
    "pricing.proYearly.f11": "500 MB Storage",
    // Plan: Professional
    "pricing.professional.name": "Professional",
    "pricing.professional.price": "89.99₾",
    "pricing.professional.yearlyPrice": "749.99₾",
    "pricing.professional.period": "/month",
    "pricing.professional.description": "For power users and career professionals.",
    "pricing.professional.cta": "Go Professional",
    "pricing.professional.f1": "Unlimited CVs",
    "pricing.professional.f2": "PDF Downloads (no watermark)",
    "pricing.professional.f3": "All Templates + Premium",
    "pricing.professional.f4": "Unlimited AI Improvements",
    "pricing.professional.f5": "Unlimited AI Full Analyses",
    "pricing.professional.f6": "Unlimited ATS Score Checks",
    "pricing.professional.f7": "Unlimited Job Tailorings",
    "pricing.professional.f8": "Cover Letter Generator",
    "pricing.professional.f9": "CV Translation",
    "pricing.professional.f10": "Unlimited Version History",
    "pricing.professional.f11": "5 GB Storage",
    // Legacy pricing keys (kept for compatibility)
    "pricing.title": "Simple, Transparent",
    "pricing.titleHighlight": "Pricing",
    "pricing.subtitle": "Join thousands of professionals landing jobs at top companies. Start for free, upgrade when you're ready.",
    "pricing.planTrial": "7-Day Free Trial",
    "pricing.planProMonthly": "Pro Monthly",
    "pricing.planProYearly": "Pro Yearly",
    "pricing.priceFree": "$0",
    "pricing.priceMonthly": "$9.99",
    "pricing.priceYearly": "$79.99",
    "pricing.perMonth": "/month",
    "pricing.perYear": "/year",
    "pricing.descTrial": "Experience full power with no credit card required.",
    "pricing.descMonthly": "Perfect for active job seekers.",
    "pricing.descYearly": "Save 33% compared to monthly billing.",
    "pricing.ctaTrial": "Start Free Trial",
    "pricing.ctaMonthly": "Go Pro Monthly",
    "pricing.ctaYearly": "Save with Yearly",
    "pricing.mostPopular": "MOST POPULAR",
    "pricing.noCardRequired": "No credit card required for the 7-day trial. Cancel anytime.",
     // Login page
  "login.title": "Welcome Back",
  "login.subtitle": "Login to your Nebula AI workspace",
  "login.continueWithGoogle": "Continue with Google",
  "login.orUseCredentials": "Or use credentials",
  "login.password": "Password",
  "login.forgotPassword": "Forgot password?",
  "login.signIn": "Sign In",
  "login.newToNebula": "New to Nebula?",
  "login.createAccount": "Create Account",
  "login.backToHome": "← Back to Home",
  "login.successMessage": "Success! Entering workspace...",
  "login.invalidCredentials": "Invalid email or password",
  "login.accountNotVerified": "Account not verified. Please check your email.",
  "login.googleFailed": "Google login failed.",

  // Register page
  "register.title": "Create Account",
  "register.checkInbox": "Check Inbox",
  "register.orSignUpManually": "Or sign up manually",
  "register.repeatPassword": "Repeat Password",
  "register.registerButton": "Register",
  "register.verifyButton": "Verify Identity",
  "register.verifying": "Verifying...",
  "register.alreadyMember": "Already a member?",
  "register.logIn": "Log In",
  "register.passwordsMismatch": "Passwords do not match",
  "register.failed": "Registration failed.",
  "register.googleFailed": "Google registration failed.",
  "register.invalidCode": "Invalid code.",
  "register.verifiedMessage": "Email verified! You're on a 7-day Pro trial. Log in to start building.",

  "placeholder.certificateName": "e.g. AWS Certified Developer",
"placeholder.issuer": "e.g. Amazon",
"placeholder.date": "MM / YYYY",
"placeholder.company": "e.g. Google",
"placeholder.jobTitle": "e.g. Software Engineer",
"placeholder.experienceDescription": "Describe your achievements...",
"placeholder.school": "e.g. Harvard University",
"placeholder.degree": "e.g. Bachelor of Science",
"placeholder.city": "e.g. London",
"placeholder.country": "e.g. UK",
"placeholder.educationDescription": "Relevant coursework or honors...",
"placeholder.projectName": "e.g. Portfolio Website",
"placeholder.projectDescription": "Describe what you built and the technologies used...",
// CONTENT PAGE
"contact.title": "Contact",
"contact.subtitle": "Have a question or want to work together? Contact us anytime.",
"contact.email": "Email",
"contact.phone": "Phone",
"contact.socialMedia": "Social Media",
"contact.address": "Address",
"contact.addressValue": "Kutaisi, St. Nino N4",
"contact.mapTitle": "Kutaisi Location",

  },
  
  ka: {
    "nav.home": "მთავარი",
    "nav.templates": "შაბლონები",
    "nav.workspace": "სამუშაო სივრცე",
    "nav.logout": "გასვლა",
    "nav.getStarted": "დაწყება",
    "nav.pricing": "ფასები",
    "nav.contact": "კონტაქტი",
    "nav.langEnglish": "GB English",
    "nav.langGeorgian": "GE ქართული",
    "resume.experience": "გამოცდილება",
    "resume.education": "განათლება",
    "resume.skills": "უნარები",
    "resume.summary": "შეჯამება",
    "resume.downloadPdf": "PDF-ის ჩამოტვირთვა",
    "resume.save": "შენახვა",
    "resume.personalInfo": "პირადი ინფორმაცია",
    "resume.professionalSummary": "პროფესიული შეჯამება",
    "resume.workExperience": "სამუშაო გამოცდილება",
    "resume.projects": "პროექტები",
    "resume.languages": "ენები",
    "resume.certificates": "სერტიფიკატები",
    "resume.present": "დღემდე",
    "dashboard.hi": "გამარჯობა",
    "dashboard.logout": "გასვლა",
    "dashboard.myWorkspace": "ჩემი სამუშაო სივრცე",
    "dashboard.my": "ჩემი",
    "dashboard.workspace": "სამუშაო სივრცე",
    "dashboard.createNewResume": "ახალი რეზიუმეს შექმნა",
    "dashboard.welcomeBack": "კეთილი იყოს თქვენი დაბრუნება",
    "dashboard.initializing": "სამუშაო სივრცის ჩატვირთვა...",
    "dashboard.freeTierActive": "უფასო ვერსია",
    "dashboard.resumes": "რეზიუმე",
    "dashboard.pdfDownloads": "PDF ჩამოტვირთვა",
    "dashboard.upgradeUnlimited": "შეუზღუდავად განახლება",
    "dashboard.workspaceEmpty": "სამუშაო სივრცე ცარიელია",
    "dashboard.workspaceEmptyDesc": "მზად ხართ სასურველი სამუშაოსთვის? აირჩიეთ შაბლონი და შექმენით რეზიუმე წუთებში.",
    "dashboard.selectTemplate": "შაბლონის არჩევა",
    "dashboard.openEditor": "რედაქტორის გახსნა",
    "dashboard.untitledResume": "უსათაურო რეზიუმე",
    "dashboard.freeLimitAlert": "უფასო ვერსიაში მხოლოდ 1 რეზიუმე. განაახლეთ Pro-ზე შეუზღუდავად!",
    "dashboard.deleteConfirm": "დარწმუნებული ხართ? ეს ვერ შეიცვლება.",
    "dashboard.duplicatePro": "რეზიუმეს დუბლირება Pro ფუნქციაა!",
    "dashboard.deleteFailed": "წაშლა ვერ მოხერხდა. სცადეთ თავიდან.",
    "dashboard.searchPlaceholder": "მოძებნე რეზიუმე...",
    "editor.resumeNamePlaceholder": "რეზიუმეს სახელი...",
    "editor.saveChanges": "ცვლილებების შენახვა",
    "editor.export": "ექსპორტი",
    "editor.generating": "იქმნება...",
    "editor.zoom": "მასშტაბი",
    "editor.saved": "შენახულია",
    "editor.syncing": "ინახება",
    "editor.unsavedChanges": "შეუნახავი ცვლილებები",
    "editor.connectionError": "შეერთების შეცდომა",
    "editor.addNewModule": "ახალი მოდულის დამატება",
    "editor.reorder": "გადაადგილება",
    "editor.addSection": "სექციის დამატება",
    "editor.classic": "კლასიკური",
    "editor.europass": "ევროპასი",
    "editor.save": "შენახვა",
    "editor.downloadPdf": "PDF-ის ჩამოტვირთვა",
    "editor.personalProfile": "პირადი პროფილი",
    "editor.addContentSection": "შიგთავსის სექციის დამატება",
    "editor.cloudSynced": "ღრუბელთან სინქრონიზებულია",
    "editor.typing": "წერაა...",
    "editor.syncError": "სინქრონიზაციის შეცდომა",
    "editor.ats": "ATS",
    "editor.tailor": "მორგება",
    "editor.improve": "გაუმჯობესება",
    "editor.analyze": "ანალიზი",
    "editor.history": "ისტორია",
    "ats.whatIs": "რა არის ATS? კომპანიები იყენებენ Applicant Tracking Systems-ს რეზიუმეების ავტომატური გაფილტვრისთვის, სანამ ადამიანი მათ ნახავს. უფრო მაღალი ქულა ნიშნავს, რომ თქვენი CV უფრო მეტ ავტომატურ ფილტრს გადის და რეკრუტერს აღწევს.",
    "ats.title": "ATS შემოწმება",
    "ats.subtitle": "Applicant Tracking System",
    "ats.proFeature": "ATS შემოწმება Pro ფუნქციაა",
    "ats.upgradeToPro": "განაახლეთ Pro-ზე ATS შესაბამისობის ქულის შესამოწმებლად და ქმედებადი რჩევების მისაღებად. 20 შემოწმება თვეში.",
    "ats.upgradeToProButton": "განახლება Pro-ზე — 29.99 ₾/თვე",
    "ats.maybeLater": "შესაძლოა მოგვიანებით",
    "ats.targetRole": "სამიზნე როლი",
    "ats.targetRoleOptional": "არასავალდებულო — ზრდის სიზუსტეს",
    "ats.industry": "ინდუსტრია",
    "ats.industryOptional": "არასავალდებულო",
    "ats.placeholderTargetRole": "მაგ. Frontend Developer",
    "ats.placeholderIndustry": "მაგ. ტექნოლოგიები",
    "ats.monthlyLimitReached": "თვიური ლიმიტი ამოწურულია",
    "ats.usedAllChecks": "თქვენ გამოიყენეთ ყველა {n} ATS შემოწმება ამ თვეში. განაახლეთ Professional-ზე შეუზღუდავი შემოწმებისთვის.",
    "ats.upgradeToProfessional": "განახლება Professional-ზე",
    "ats.runCheck": "ATS შემოწმება",
    "ats.rerunCheck": "ხელახლა შემოწმება",
    "ats.left": "დარჩა",
    "ats.checkFailed": "ATS შემოწმება ვერ მოხერხდა. სცადეთ თავიდან.",
    "ats.checkProFeature": "ATS შემოწმება Pro ფუნქციაა. განახლებისთვის განაგრძეთ.",
    "tailor.title": "სამუშაოს მორგება",
    "tailor.intro": "ჩასვით სამუშაოს აღწერა და AI შეცვლის შესაბამის სექციებს როლის საკვანძო სიტყვების შესაბამისად. ცვლილება არ მოხდება სანამ Apply-ზე არ დააჭერთ.",
    "tailor.jobTitle": "სამუშაოს პოზიცია",
    "tailor.placeholderJobTitle": "მაგ. Senior Frontend Dev",
    "tailor.company": "კომპანია",
    "tailor.placeholderCompany": "მაგ. Google",
    "tailor.jobDescription": "სამუშაოს აღწერა",
    "tailor.placeholderJobDescription": "ჩასვით სრული სამუშაოს აღწერა აქ. უფრო მეტი დეტალი = უკეთესი შესაბამისობა.",
    "tailor.pasteJob": "სამუშაოს აღწერა მორგებისთვის…",
    "tailor.tailoring": "CV-ის მორგება…",
    "tailor.tailorMyCv": "ჩემი CV-ის მორგება",
    "tailor.strongMatch": "ძლიერი შესაბამისობა",
    "tailor.decentMatch": "კარგი შესაბამისობა",
    "tailor.weakMatch": "სუსტი შესაბამისობა",
    "tailor.failed": "მორგება ვერ მოხერხდა. სცადეთ თავიდან.",
    "improve.title": "AI გაუმჯობესება",
    "improve.pickSection": "აირჩიეთ სექცია გასაუმჯობესებლად",
    "improve.pickSectionDesc": "აირჩიეთ სექცია. AI გადაწერს მას — ნახავთ ორიგინალს და წინადადებას გვერდიგვერდ, და შეგიძლიათ რედაქტირება გამოყენებამდე.",
    "improve.generatingSuggestion": "წინადადების მომზადება…",
    "improve.reviewBeforeApplying": "განიხილეთ გამოყენებამდე",
    "improve.upgradeToContinue": "განაგრძეთ განახლებისთვის",
    "improve.clickToImprove": "დააწკაპუნეთ AI-ით გასაუმჯობესებლად",
    "improve.improving": "გაუმჯობესება: {section}…",
    "improve.gptRewriting": "GPT-4 გადაწერავს თქვენს შიგთავსს",
    "improve.usuallyTakes": "ჩვეულებრივ 3–5 წამი",
    "improve.backToSections": "სექციებზე დაბრუნება",
    "improve.aiSuggestionsFor": "AI წინადადებები {section}-ისთვის",
    "improve.originalContent": "ორიგინალი შიგთავსი",
    "improve.aiImprovedVersion": "AI-ით გაუმჯობესებული ვერსია",
    "improve.applySuggestions": "წინადადებების გამოყენება",
    "improve.editBeforeApplying": "რედაქტირება გამოყენებამდე",
    "improve.reject": "უარყოფა",
    "improve.tryDifferent": "სხვა ვერსიის სცადება",
    "analyze.title": "CV ანალიზი",
    "analyze.subtitle": "საერთო შესაბამისობა და რეკომენდაციები",
    "analyze.whatDoes": "რას აკეთებს? აანალიზებს თქვენს CV-ს სამუშაოს აღწერასთან შედარებით და აბრუნებს საერთო ქულას, ძლიერ მხარეებს, გასაუმჯობესებელ ადგილებს და ATS ჩანაწერებს. არასავალდებულო: ჩასვით სამუშაოს აღწერა სამიზნე გამოხმაურებისთვის.",
    "analyze.jobDescription": "სამუშაოს აღწერა",
    "analyze.jobDescriptionOptional": "არასავალდებულო",
    "analyze.placeholder": "ჩასვით სამუშაოს აღწერა ანალიზისთვის…",
    "analyze.analyzeAgain": "შეამოწმეთ თავიდან",
    "analyze.upgradeRequired": "CV ანალიზი შეზღუდულია უფასო გეგმაზე. განაგრძეთ განახლებისთვის.",
    "analyze.failed": "CV ანალიზი ვერ მოხერხდა. სცადეთ თავიდან.",
    "history.title": "ვერსიების ისტორია",
    "history.notAvailable": "ვერსიების ისტორია უფასო გეგმაზე მიუწვდომელია.",
    "history.upgradeToSave": "განაახლეთ Pro-ზე სნეპშოტების შესანახად და წინა ვერსიების აღსადგენად.",
    "history.upgradeToPro": "განახლება Pro-ზე",
    "history.limitReached": "ვერსიების ლიმიტი ამოწურულია. მეტი ისტორიისთვის განაახლეთ.",
    "history.failedToLoad": "ვერსიების ჩატვირთვა ვერ მოხერხდა.",
    "history.failedToSave": "ვერსიის შენახვა ვერ მოხერხდა.",
    "history.failedToRestore": "ვერსიის აღდგენა ვერ მოხერხდა.",
    "form.fullName": "სრული სახელი *",
    "form.jobTitle": "სამუშაო პოზიცია",
    "form.email": "ელფოსტა",
    "form.phone": "ტელეფონი",
    "form.location": "მისამართი",
    "form.linkedin": "LinkedIn",
    "form.profilePicture": "პროფილის ფოტო",
    "form.profilePictureHint": "პროფესიული ფოტოები ხილვადობას ზრდის.",
    "form.square": "კვადრატი",
    "form.circle": "წრე",
    "form.company": "კომპანია",
    "form.startDate": "დაწყების თარიღი",
    "form.endDate": "დასრულების თარიღი",
    "form.currentlyWorking": "ახლა აქ ვმუშაობ",
    "form.description": "აღწერა",
    "form.addEntry": "ჩანაწერის დამატება",
    "form.deleteSection": "სექციის წაშლა",
    "form.aiImprove": "AI გაუმჯობესება",
    "form.addSkill": "უნარის დამატება",
    "form.schoolUniversity": "სკოლა / უნივერსიტეტი",
    "form.degreeMajor": "ხარისხი / სპეციალობა",
    "form.city": "ქალაქი",
    "form.country": "ქვეყანა",
    "form.addEducation": "განათლების დამატება",
    "form.addProject": "პროექტის დამატება",
    "form.addLanguage": "ენის დამატება",
    "form.addCertificate": "სერტიფიკატის დამატება",
    "form.projectName": "პროექტის სახელი",
    "form.projectLink": "პროექტის ბმული (არასავალდებულო)",
    "form.certificateName": "სერტიფიკატის სახელი",
    "form.issuer": "გამომცემელი (მაგ. Google)",
    "form.date": "თარიღი",
    "form.deleteSectionConfirm": "მთელი ეს სექცია წავშალოთ?",
    "form.deleteExperienceConfirm": "დარწმუნებული ხართ, რომ გსურთ მთელი",
    "form.section": "სექციის წაშლა?",
    "landing.badge": "AI-გაძლიერებული რეზიუმეს ამწყობი",
    "landing.heroTitle": "შექმენი",
    "landing.heroTitleHighlight": "ბრწინვალე რეზიუმე",
    "landing.heroTitleEnd": "რომელიც დაგეხმარებათ დასაქმებაში.",
    "landing.heroSubtitle": "შექმენით პროფესიული რეზიუმე წუთებში AI-ით და დიზაინერების შაბლონებით.",
    "landing.getStartedFree": "დაიწყეთ უფასოდ",
    "landing.goToDashboard": "სამუშაო სივრცეში",
    "landing.browseTemplates": "შაბლონების ნახვა",
    "landing.buildYourFuture": "ააშენეთ თქვენი მომავალი",
    "landing.ctaTitle": "მზად ხართ საოცნებო რეზიუმეს შესაქმნელად?",
    "landing.ctaSubtitle": "შემოუერთდით ათასობით პროფესიონალს, რომლებმაც ჩვენი AI რეზიუმე ბილდერით იშოვეს სამუშაო",
    "landing.ctaButton": "დაიწყეთ ახლავე",
    "landing.footerTagline": "შექმენით ნათელი რეზიუმე ყველა სამუშაო სამყაროში.",
    "landing.footerBrand": "Nebula AI CV ბილდერი",
    "landing.footerCopyright": "© 2025 Nebula AI. ყველა უფლება დაცულია.",
    "landing.footerPrivacy": "კონფიდენციალურობა",
    "landing.footerTerms": "პირობები",
    "landing.footerContact": "კონტაქტი",
    "landing.featuresTitle": "ყველაფერი რაც სჭირდებათ იდეალური რეზიუმესთვის",
    "landing.featuresSubtitle": "ფუნქციები, რომლებიც დაგეხმარებათ პროფესიული რეზიუმეს შექმნაში",
    "landing.feature1Title": "პროფესიული შაბლონი",
    "landing.feature1Desc": "სუფთა, ATS-მეგობრული კლასიკური შაბლონი მაქსიმალური ეფექტისთვის.",
    "landing.feature2Title": "სრული კასტომიზაცია",
    "landing.feature2Desc": "ფერები, შრიფტები და ლეიაუტი თქვენი ბრენდის შესატყვისად.",
    "landing.feature3Title": "PDF ექსპორტი",
    "landing.feature3Desc": "ჩამოტვირთეთ რეზიუმე მაღალი ხარისხის PDF-ად.",
    "landing.feature4Title": "AI-ზე დაფუძნებული",
    "landing.feature4Desc": "ჭკვიანი წინადადებები რეზიუმეს გასაუმჯობესებლად.",
    "landing.feature5Title": "უსაფრთხო და პირადი",
    "landing.feature5Desc": "მონაცემები დაშიფრული და უსაფრთხოდ ინახება.",
    "landing.feature6Title": "სწრაფი კლონირება / ვერსიები",
    "landing.feature6Desc": "შექმენით ამ CV-ის ზუსტი ასლი სხვა სამუშაოსთვის მორგებისთვის ან მიმდინარე პროგრესის შეკრულებისთვის.",
    "landing.learnMore": "გაიგე მეტი",
    "templates.chooseStyle": "აირჩიეთ სტილი",
    "templates.chooseFoundation": "აირჩიეთ საფუძველი",
    "templates.chooseFoundationSub": "შემდეგი თავისთვის.",
    "templates.subtitle": "ჩვენი შაბლონები არა მხოლოდ დიზაინია—ისინი სტრატეგიული ინსტრუმენტებია.",
    "templates.backToDashboard": "სამუშაო სივრცეში დაბრუნება",
    "templates.backToHome": "მთავარზე დაბრუნება",
    "templates.professional": "პროფესიული",
    "templates.creative": "შემოქმედებითი",
    "templates.academic": "აკადემიური",
    "templates.aiOptimized": "AI ოპტიმიზებული",
    "templates.selectDesign": "აირჩიეთ დიზაინი",
    "templates.initializing": "იქმნება...",
    "templates.interchangeable": "ყველა შაბლონი ურთიერთშემცვლელია. ლეიაუტის შეცვლა შეგიძლიათ ნებისმიერ დროს.",
    "templates.proBadge": "Pro",
    "templates.upgradeToUnlock": "განახლება გასახსნელად",
    "templates.europassName": "ევროპასი მოდერნი",
    "templates.europassRole": "საერთაშორისო და ინსტიტუციური",
    "templates.europassSummary": "ოქროს სტანდარტი EU საჯარო სექტორისთვის, მედიცინისა და აკადემიისთვის.",
    "templates.europassIntro": "შექმნილი რთული კრედენციალებისთვის. ევროკომისიის ოფიციალურ სტანდარტებს მიჰყვება.",
    "templates.europassF1": "EU სტანდარტებთან შესაბამისი",
    "templates.europassF2": "მრავალგვერდიანი ოპტიმიზაცია",
    "templates.europassF3": "აკადემიური სტრუქტურა",
    "templates.classicName": "კლასიკური პროფესიონალი",
    "templates.classicRole": "კორპორატიული და ექსეკუტიული",
    "templates.classicSummary": "ოპტიმიზებული ტექნოლოგიის, ფინანსების და ლიდერული როლებისთვის.",
    "templates.classicIntro": "პრეციზიული ლეიაუტი ATS-ის გასაფილტრად და რეკრუტერებისთვის.",
    "templates.classicF1": "99% ATS გავლა",
    "templates.classicF2": "ექსეკუტიული წაკითხვადობა",
    "templates.classicF3": "შედეგზე ორიენტირებული",
    // Pricing Page
    "pricing.heroTitle": "მარტივი, გამჭვირვალე",
    "pricing.heroTitleHighlight": "ფასები",
    "pricing.heroSubtitle": "ფასები ₾ ლარში · დამალული საკომისიო არ არის",
    "pricing.heroSubtitleLine2": "გაუქმება ნებისმიერ დროს.",
    "pricing.trialBanner": "გრჩებათ",
    "pricing.trialBannerDays": "დღე",
    "pricing.trialBannerDaysPlural": "დღე",
    "pricing.trialBannerEnd": "უფასო Pro ტრიალიდან. განაახლეთ ახლა ყველა ფუნქციის შესანარჩუნებლად.",
    "pricing.currentPlan": "მიმდინარე გეგმა",
    "pricing.enterpriseTitle": "საჭიროა Enterprise?",
    "pricing.enterpriseDesc": "გუნდური თანამშრომლობა, white label, API წვდომა, მორგებული საცავი,",
    "pricing.enterpriseDescLine2": "და სატელეფონო მხარდაჭერა. ფასი მოთხოვნით.",
    "pricing.enterpriseCta": "დაუკავშირდით გაყიდვებს",
    "pricing.trialBadge": "ახალი ანგარიშები იღებენ 7-დღიან Pro ტრიალს — ბარათის გარეშე",
    "pricing.paymentError": "გადახდის ინიციალიზაცია ვერ მოხერხდა. სცადეთ თავიდან.",
    // Plan: Free
    "pricing.free.name": "უფასო",
    "pricing.free.price": "0₾",
    "pricing.free.description": "დაიწყეთ საბაზო ფუნქციებით. საკრედიტო ბარათი არ სჭირდება.",
    "pricing.free.cta": "დაიწყეთ უფასოდ",
    "pricing.free.f1": "მაქსიმუმ 2 CV",
    "pricing.free.f2": "PDF ჩამოტვირთვა (წყლის ნიშნით)",
    "pricing.free.f3": "2 შაბლონი (Classic & Europass)",
    "pricing.free.f4": "5 AI გაუმჯობესება სექციაზე",
    "pricing.free.f5": "5 AI სრული ანალიზი სულ",
    "pricing.free.f6": "ATS ქულის შემოწმება",
    "pricing.free.f7": "სამუშაოს მორგება",
    "pricing.free.f8": "სამოტივაციო წერილის გენერატორი",
    "pricing.free.f9": "CV თარგმნა",
    "pricing.free.f10": "ვერსიების ისტორია",
    "pricing.free.f11": "10 MB საცავი",
    // Plan: Pro Monthly
    "pricing.proMonthly.name": "Pro",
    "pricing.proMonthly.price": "29.99₾",
    "pricing.proMonthly.period": "/თვე",
    "pricing.proMonthly.description": "ყველაფერი, რაც სჭირდება შემდეგი სამუშაოს საპოვნელად.",
    "pricing.proMonthly.cta": "დაიწყეთ Pro ყოველთვიური",
    "pricing.proMonthly.badge": "ყველაზე პოპულარული",
    "pricing.proMonthly.f1": "მაქსიმუმ 20 CV",
    "pricing.proMonthly.f2": "PDF ჩამოტვირთვა (წყლის ნიშნის გარეშე)",
    "pricing.proMonthly.f3": "2 შაბლონი (Classic & Europass)",
    "pricing.proMonthly.f4": "შეუზღუდავი AI გაუმჯობესება",
    "pricing.proMonthly.f5": "100 AI სრული ანალიზი / თვე",
    "pricing.proMonthly.f6": "20 ATS ქულის შემოწმება / თვე",
    "pricing.proMonthly.f7": "50 სამუშაოს მორგება / თვე",
    "pricing.proMonthly.f8": "სამოტივაციო წერილის გენერატორი",
    "pricing.proMonthly.f9": "CV თარგმნა",
    "pricing.proMonthly.f10": "ბოლო 10 ვერსიის ისტორია",
    "pricing.proMonthly.f11": "500 MB საცავი",
    // Plan: Pro Yearly
    "pricing.proYearly.name": "Pro წლიური",
    "pricing.proYearly.price": "239.99₾",
    "pricing.proYearly.period": "/წელი",
    "pricing.proYearly.description": "იგივე, რაც Pro ყოველთვიური — დაზოგეთ ~2 თვე უფასოდ.",
    "pricing.proYearly.cta": "დაიწყეთ Pro წლიური",
    "pricing.proYearly.badge": "დაზოგეთ ~33%",
    "pricing.proYearly.f1": "მაქსიმუმ 20 CV",
    "pricing.proYearly.f2": "PDF ჩამოტვირთვა (წყლის ნიშნის გარეშე)",
    "pricing.proYearly.f3": "2 შაბლონი (Classic & Europass)",
    "pricing.proYearly.f4": "შეუზღუდავი AI გაუმჯობესება",
    "pricing.proYearly.f5": "100 AI სრული ანალიზი / თვე",
    "pricing.proYearly.f6": "20 ATS ქულის შემოწმება / თვე",
    "pricing.proYearly.f7": "50 სამუშაოს მორგება / თვე",
    "pricing.proYearly.f8": "სამოტივაციო წერილის გენერატორი",
    "pricing.proYearly.f9": "CV თარგმნა",
    "pricing.proYearly.f10": "ბოლო 10 ვერსიის ისტორია",
    "pricing.proYearly.f11": "500 MB საცავი",
    // Plan: Professional
    "pricing.professional.name": "პროფესიონალი",
    "pricing.professional.price": "89.99₾",
    "pricing.professional.yearlyPrice": "749.99₾",
    "pricing.professional.period": "/თვე",
    "pricing.professional.description": "ძლიერი მომხმარებლებისა და კარიერის პროფესიონალებისთვის.",
    "pricing.professional.cta": "გახდით პროფესიონალი",
    "pricing.professional.f1": "შეუზღუდავი CV",
    "pricing.professional.f2": "PDF ჩამოტვირთვა (წყლის ნიშნის გარეშე)",
    "pricing.professional.f3": "ყველა შაბლონი + Premium",
    "pricing.professional.f4": "შეუზღუდავი AI გაუმჯობესება",
    "pricing.professional.f5": "შეუზღუდავი AI სრული ანალიზი",
    "pricing.professional.f6": "შეუზღუდავი ATS ქულის შემოწმება",
    "pricing.professional.f7": "შეუზღუდავი სამუშაოს მორგება",
    "pricing.professional.f8": "სამოტივაციო წერილის გენერატორი",
    "pricing.professional.f9": "CV თარგმნა",
    "pricing.professional.f10": "შეუზღუდავი ვერსიების ისტორია",
    "pricing.professional.f11": "5 GB საცავი",
    // Legacy pricing keys (kept for compatibility)
    "pricing.title": "მარტივი, გამჭვირვალე",
    "pricing.titleHighlight": "ფასები",
    "pricing.subtitle": "შემოუერთდით პროფესიონალებს. დაიწყეთ უფასოდ, განაახლეთ როცა მზად ხართ.",
    "pricing.planTrial": "7-დღიანი უფასო ტრიალი",
    "pricing.planProMonthly": "Pro ყოველთვიური",
    "pricing.planProYearly": "Pro წლიური",
    "pricing.priceFree": "$0",
    "pricing.priceMonthly": "$9.99",
    "pricing.priceYearly": "$79.99",
    "pricing.perMonth": "/თვე",
    "pricing.perYear": "/წელი",
    "pricing.descTrial": "სრული ძალა ბარათის გარეშე.",
    "pricing.descMonthly": "იდეალური აქტიური მაძიებლებისთვის.",
    "pricing.descYearly": "დაზოგეთ 33% ყოველთვიურთან შედარებით.",
    "pricing.ctaTrial": "დაიწყეთ ტრიალი",
    "pricing.ctaMonthly": "Pro ყოველთვიური",
    "pricing.ctaYearly": "დაზოგეთ წლიური",
    "pricing.mostPopular": "ყველაზე პოპულარული",
    "pricing.noCardRequired": "7-დღიანი ტრიალი ბარათის გარეშე. გაუქმება ნებისმიერ დროს.",
    "pricing.paymentError": "შეცდომა გადახდის სისტემასთან დაკავშირებაში.",
    // Common actions
    "common.cancel": "გაუქმება",
    "common.confirm": "დადასტურება",
    // Login page
  "login.title": "კეთილი იყოს დაბრუნება",
  "login.subtitle": "შედით Nebula AI სამუშაო სივრცეში",
  "login.continueWithGoogle": "Google-ით გაგრძელება",
  "login.orUseCredentials": "ან გამოიყენეთ მონაცემები",
  "login.password": "პაროლი",
  "login.forgotPassword": "დაგავიწყდათ პაროლი?",
  "login.signIn": "შესვლა",
  "login.newToNebula": "პირველად Nebula-ზე?",
  "login.createAccount": "ანგარიშის შექმნა",
  "login.backToHome": "← მთავარზე დაბრუნება",
  "login.successMessage": "წარმატება! სამუშაო სივრცეში შესვლა...",
  "login.invalidCredentials": "არასწორი ელფოსტა ან პაროლი",
  "login.accountNotVerified": "ანგარიში დაუდასტურებელია. შეამოწმეთ ელფოსტა.",
  "login.googleFailed": "Google-ით შესვლა ვერ მოხერხდა.",

  // Register page
  "register.title": "ანგარიშის შექმნა",
  "register.checkInbox": "შეამოწმეთ შემოსული",
  "register.orSignUpManually": "ან დარეგისტრირდით ხელით",
  "register.repeatPassword": "გაიმეორეთ პაროლი",
  "register.registerButton": "რეგისტრაცია",
  "register.verifyButton": "ვინაობის დადასტურება",
  "register.verifying": "მოწმდება...",
  "register.alreadyMember": "უკვე წევრი ხართ?",
  "register.logIn": "შესვლა",
  "register.passwordsMismatch": "პაროლები არ ემთხვევა",
  "register.failed": "რეგისტრაცია ვერ მოხერხდა.",
  "register.googleFailed": "Google-ით რეგისტრაცია ვერ მოხერხდა.",
  "register.invalidCode": "არასწორი კოდი.",
  "register.verifiedMessage": "ელფოსტა დადასტურდა! გაქვთ 7-დღიანი Pro ტრიალი. შედით და დაიწყეთ.",

  "placeholder.certificateName": "მაგ. AWS Certified Developer",
"placeholder.issuer": "მაგ. Amazon",
"placeholder.date": "თთ / წწწწ",
"placeholder.company": "მაგ. Google",
"placeholder.jobTitle": "მაგ. Software Engineer",
"placeholder.experienceDescription": "აღწერეთ თქვენი მიღწევები...",
"placeholder.school": "მაგ. თბილისის სახელმწიფო უნივერსიტეტი",
"placeholder.degree": "მაგ. ბაკალავრი, კომპიუტერული მეცნიერება",
"placeholder.city": "მაგ. თბილისი",
"placeholder.country": "მაგ. საქართველო",
"placeholder.educationDescription": "შესაბამისი კურსები ან პატივი...",
"placeholder.projectName": "მაგ. პორტფოლიო საიტი",
"placeholder.projectDescription": "აღწერეთ რა ააშენეთ და რა ტექნოლოგიები გამოიყენეთ...",
// CONTENT PAGE
"contact.title": "კონტაქტი",
"contact.subtitle": "გაქვთ კითხვა ან გსურთ თანამშრომლობა? დაგვიკავშირდით ნებისმიერ დროს.",
"contact.email": "ელფოსტა",
"contact.phone": "ტელეფონი",
"contact.socialMedia": "სოციალური მედია",
"contact.address": "მისამართი",
"contact.addressValue": "ქუთაისი, წმ. ნინოს N4",
"contact.mapTitle": "ქუთაისის მდებარეობა",

  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      if (stored === "en" || stored === "ka") return stored;
    } catch (_) {}
    return "en";
  });

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, language);
    } catch (_) {}
  }, [language]);

  const setLanguage = useCallback((lang) => {
    if (lang === "en" || lang === "ka") setLanguageState(lang);
  }, []);

  const t = (key) => {
    return translations[language]?.[key] ?? translations.en[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context)
    throw new Error("useLanguage must be used within a LanguageProvider");
  return context;
};